apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: dailylog
  labels:
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: backend
  template:
    metadata:
      name: back-pod
      labels:
        tier: backend
    spec:
      containers:
      - name: backend-container
        image: kva231/dailylog-backend:1.0
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 250m
            memory: 64Mi
        ports:
        - containerPort: 8000
        env: 
        - name: DAILYLOG_DB_ADDR
          value: root:k8spass#@dailylogcluster.cluster-cpp56kcoe5lo.ap-northeast-2.docdb.amazonaws.com:27017
        - name: DAILYLOG_DB_ADDR_QUERYSTRING
          value: ?ssl=true&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false
      terminationGracePeriodSeconds: 300

---

apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: dailylog
spec:
  selector:
    tier: backend
  ports:
  - port: 8000
    targetPort: 8000
