apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: dailylog
  labels:
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:  
      tier: frontend
  template:
    metadata:
      name: front-pod
      labels:
        tier: frontend
    spec:
      containers:
      - name: frontend-container
        image: kva231/dailylog-frontend:1.0
        ports:
        - containerPort: 8000
        env:
        - name: DAILYLOG_API_ADDR
          value: backend:8000

---

apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: dailylog
spec:
  selector: 
    tier: frontend
  type: LoadBalancer
  ports:
  - port: 8000
    targetPort: 8000
